site:
  tab: HAMELV-FR # Text displayed in the browser tab
  title: HAMELV-FR # Website title
  description: ğŸ‘‹ Bienvenue sur mon site ! Vous y trouverez mes projets GitHub ğŸ’» et ma veille technologique ğŸ” â€” un espace personnel pour partager mes rÃ©alisations et les tendances du monde numÃ©rique ğŸŒ # Website description for SEO
  language: fr # Website language code, e.g., "en" for English, "zh" for Chinese
  favicon: /favicon.ico # Website favicon path
  theme:
    light: winter # Light mode theme, based on daisyUI themes
    dark: dracula # Dark mode theme, based on daisyUI themes
    code: github-dark # Code block theme style
  date_format: ddd MMM DD YYYY # Date display format
  blog: 
    pageSize: 8 
  menu: 
    - id: home           # Identifiant unique
      text: "Accueil"  # LibellÃ© affichÃ©
      href: "/"          # Lien
      svg: "material-symbols:home-outline-rounded"   # IcÃ´ne
      target: _self      # Cible du lien
    - id: news
      text: "ActualitÃ©Â IT"
      href: "/actualite-it"
      svg: "material-symbols:feed-outline"
      target: _self
    - id: security
      text: "ANSSIÂ &Â CVE"
      href: "/anssi-cve"
      svg: "material-symbols:shield-outline"
      target: _self
    - id: tutorials
      text: "Tutoriels"
      href: "/blog"
      svg: "material-symbols:school-outline"
      target: _self
    - id: github
      text: "ProjetsÂ GitHub"
      href: "https://github.com/ITvenn"   # Remplacez par votre URL GitHub
      svg: "ri:github-fill"
      target: _blank
    - id: about
      text: "Ã€ propos de moi"
      href: "/about"
      svg: "material-symbols:person-outline-rounded"
      target: _self

user:
  name: ITvenn # User's name
  site: "https://www.hamelv.fr" # User's personal website URL
  avatar: /profile.png # User avatar
  sidebar:
    social:
      - href: "https://www.linkedin.com/in/vincent-hamel-9b9422229"
        ariaLabel: LinkedIn
        title: LinkedIn
        svg: "ri:linkedin-line"
      - href: "https://github.com/ITvenn"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://tryhackme.com/p/ITvenn"
        ariaLabel: TryHackMe
        title: TryHackMe
        svg: "ri:shield-line"

  footer:
    social:
      - href: "https://www.linkedin.com/in/vincent-hamel-9b9422229"
        ariaLabel: LinkedIn
        title: LinkedIn
        svg: "ri:linkedin-line"
      - href: "https://github.com/ITvenn"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://tryhackme.com/p/ITvenn"
        ariaLabel: TryHackMe
        title: TryHackMe
        svg: "ri:shield-line"
